{% set name = "yajl-ruby" %}
{% set version = "1.4.2" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 8228a1de1b53e346de619c5dcb0ed2ac82cc4c9ca6b0a41fc5bae98ee2c7cc51

build:
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies -n $PREFIX/bin {{ name }}-{{ version }}.gem && gem unpack {{ name }}-{{ version }}.gem && make -C {{ PREFIX }}/lib/ruby/gems/{{ ruby }}.0/gems/{{ name }}-{{ version }}/ext/yajl clean
  skip: {{ win }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}

test:
  commands:
    - ruby -r yajl -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: Ruby C bindings to the excellent Yajl JSON stream-based parser library.
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/brianmario/yajl-ruby

extra:
  recipe-maintainers:
    - mxr-conda
    - conda-forge/ruby
