travis:
  secure:
    BINSTAR_TOKEN: ZTB7C18ci6D+tF2bMyKVhCgWbvfUpdSBfgfWh9yX6gIT21Ncq4d5k4oJNrKhO3f9SOJgPApsANx+LmDKznLv9E6Me8t7W+yv/Hnpjw8+xzEvX8bXqrq0YtUNSYe+WG78SPQIOA4wFY3+9DvSxYj0T1x9n6gH/BIqLA2guulltUmTp9Z9uGn+ULrxGdkIImH7useitTy7YBHRIMZC09y/qiFwmvL4SNP9WdoI440guTDomDy3by4hn+anFeQXGVogEgxHQUb2T9uRWaEm9DircPKX8d2Nl+ghKEgUkaJwgSUYJu7rwnhe4loTnfAVn+RQH+h99E1P/BPcJIRyDrkJ0PPKsc4hm+MZkz1qCn2aWr9Jgb2K34TpyQJWXkJH/0XNvYV/yQtzKxkQextuQyyBQleQCfS6hAk6JaEthjnnqR/v7Bd3vWNfl1dEf/Z5HnXYu1PZmF2gxBrVu9xrJRpJAPjqFst/sIi0bvMtoA0fYOV5bpc2tx6h8t4ZlgE6J1j0tohVd5xkMIuFqUo+oxY3P+SIS+lP6xo/91lFy7MQ9DGqz/lk/UpaqhGk3RdWTnky/wE4ZsdntGxRuc2VYgkXzRh1GV1E2ZIH2eBVPWvLF7YotYCfdYhp83x8y50JUjiDcU2hd+zU4XhCSsNZv8GHAXrYVvh9mZxQLNfmr6LiWyQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
